version: "3.9"
services:
  cad:
    build: .
    restart: always
    ports:
      - "3030:3030"
    environment: 
      DB_HOST: "${DB_HOST}"
      DB_NAME: "${DB_NAME}"
      DB_PASSWORD: "${DB_PASSWORD}"
      JWT_SECRET: "${JWT_SECRET}"
      PORT: 3030
    healthcheck:
      test: curl -sS http://cad:3030/health/liveness || exit 1
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 60s
    depends_on:
      database:
        condition: service_healthy
  admin:
    image: "phpmyadmin:5.1.0"
    restart: always
    ports:
      - "8080:80"
    environment: 
      PMA_HOST: "${DB_HOST}"
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
    depends_on:
      database:
        condition: service_healthy
  database:
    image: "mysql:5.7"
    volumes:
      - db_data:/var/lib/mysql
      - ./snaily-cad.sql:/docker-entrypoint-initdb.d/001_init.sql
    restart: always
    ports:
      - "3306:3306"
    environment: 
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
    healthcheck:
      test: "/etc/init.d/mysql status"
      timeout: 5s
      retries: 3
volumes:
  db_data: {}
